# Generated by Django 4.2.7 on 2025-07-31 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Developer', 'Developer'), ('Tester', 'Tester')], max_length=255),
        ),
    ]
